REMINDER_DAYS = 10
PREMIUM_DURATION = 3
BASE_DURATION = 1
DATE_FORMAT = "%d-%m-%Y"
PREMIUM = "PREMIUM"
INVALID_DATE = "INVALID_DATE"

START_SUBSCRIPTION = "START_SUBSCRIPTION"
ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION"
RENEWAL_REMINDER = "RENEWAL_REMINDER"
RENEWAL_AMOUNT = "RENEWAL_AMOUNT"
ADD_TOPUP = "ADD_TOPUP"
PRINT_RENEWAL_DETAILS = "PRINT_RENEWAL_DETAILS"
SUBSCRIPTIONS_NOT_FOUND = "SUBSCRIPTIONS_NOT_FOUND"
ADD_SUBSCRIPTION_FAILED = "ADD_SUBSCRIPTION_FAILED "
ADD_TOPUP_FAILED = "ADD_TOPUP_FAILED "

SUBSCRIPTION_INVALID_DATE = ADD_SUBSCRIPTION_FAILED + INVALID_DATE
DUPLICATE_CATEGORY = ADD_SUBSCRIPTION_FAILED + "DUPLICATE_CATEGORY"

DUPLICATE_TOPUP = ADD_TOPUP_FAILED + "DUPLICATE_TOPUP"
TOPUP_INVALID_DATE = ADD_TOPUP_FAILED + INVALID_DATE
TOPUP_NO_SUSCRIPTION = ADD_TOPUP_FAILED + SUBSCRIPTIONS_NOT_FOUND

VALID_DATE = "VALID_DATE"
VALID = "VALID"

SUBSCRIPTION_PLANS = {  "MUSIC" : {"FREE":0, "PERSONAL":100, "PREMIUM":250},
                        "VIDEO" : {"FREE":0, "PERSONAL":200, "PREMIUM":500},
                        "PODCAST" : {"FREE":0, "PERSONAL":100, "PREMIUM":300}
                    }
TOPUP_PLANS = {"FOUR_DEVICE": 50, "TEN_DEVICE":100}